package com.gianlu.timeless.main;

public enum DrawerItem {
    COMMITS, PROJECTS, PUBLIC_LEADERBOARD,
    PREFERENCES, SUPPORT, DAILY_STATS,
    PRIVATE_LEADERBOARDS, LIFETIME_STATS,
    CUSTOM_RANGE_STATS
}
