version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.github.triplet.play
    versions:
    - 3.2.0-agp4.2-2
    - 3.3.0-agp4.2
    - 3.4.0-agp7.0
  - dependency-name: com.google.firebase:firebase-crashlytics-gradle
    versions:
    - 2.5.0
    - 2.5.1
  - dependency-name: com.google.firebase:firebase-perf
    versions:
    - 19.1.1
  - dependency-name: com.google.android.material:material
    versions:
    - 1.3.0
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
